### ISSUE TITLE
Successfully program an iCE40.

### ISSUE THREAD

**Issue by ahmedcharles** [icebreaker-fpga/icebreaker-v2-usb-firmware#1]
Steps:

 - [x] #2 
 - [x] #3

**Comment by gregdavill** [comment]
An approach that I think was mentioned in discord.

 - [ ] Get USB DFU example running
 - [ ] Implement SPI transfer into the iCE40 instead of the typical writing to internal FLASH.

This way the PC software is already handled with dfu-util.

Looks like cherryUSB has a device class setup for DFU 
https://github.com/sakumisu/CherryUSB/blob/master/demo/ch32/usb_device/CH32V307VCT6/CherryUSB/class/dfu/usbd_dfu.c

**Comment by sakumisu** [comment]
> Looks like cherryUSB has a device class setup for DFU, but no full examples https://github.com/sakumisu/CherryUSB/blob/master/demo/ch32/usb_device/CH32V307VCT6/CherryUSB/class/dfu/usbd_dfu.c

Hi,i saw this, dfu demo needs to be used with the pc software , i will release a simple demo later.

**Comment by perigoso** [comment]
Tinyusb also has a dfu class implemented, i think the example is lacking too though

**Comment by esden** [comment]
In all honesty, I would love if we can use this opportunity to improve the Rust support for these parts instead. There is a crate that implements the DFU device side that we should be able to use, expand and contribute to. https://crates.io/crates/usbd-dfu-rt

**Comment by esden** [comment]
Yes I know this firmware is currently all written in C ... and that is very much appreciated. Don't take it as "rewrite it in rust" comment. I just wish I had more time to work on a Rust firmware myself. :D

**Comment by sakumisu** [comment]
Rewrite cherryusb in rust, right? This is a trend,but need sometime becasue i am not very familiar with rust, and it depends on other peripheral like clock  or pin,those need to be rewrited too.

**Comment by gregdavill** [comment]
I've had some time this week to fix up my tinyusb port, some bugs in there around EP0 IN transfers. 

It's in a state now where it presents 2 ALT interfaces via DFU. Loading an ice40 bitstream into the first writes it to FLASH, into the second loads it directly into the ice40's configuration SRAM. This takes 1s and 150ms for a 100kB "blinky" bitstream respectively.

**Comment by gregdavill** [comment]
Got that beautiful blue glow of the "CDONE" LED, showing that the FPGA is configured! :D

![FcL4vFAacAAMthm](https://user-images.githubusercontent.com/344310/189356213-e288b3b2-48a8-4a7c-828c-bc648a905b33.jpeg)

**Comment by sakumisu** [comment]
> Looks like cherryUSB has a device class setup for DFU, but no full examples https://github.com/sakumisu/CherryUSB/blob/master/demo/ch32/usb_device/CH32V307VCT6/CherryUSB/class/dfu/usbd_dfu.c

DFU demo has done
