### ISSUE TITLE
some doubts

### ISSUE THREAD

**Issue by Alvazz** [icebreaker-fpga/icebreaker-v2-usb-firmware#9]
Honestly, I'm a newbie and I don't understand what this repository description means?

"Firmware to implement USB communications on the CH32V307 microcontroller"

Does the passage written in the introduction refer to a chip (for example, we call it an ABC chip) to establish communication with CH32V307? Does the ABC chip get the data transmitted by the USB from the CH32V307? is that so? Or am I getting it wrong.

**Comment by dragonmux** [comment]
There's no "ABC" chip involved here, this firmware is for the CH32V307 - ie, you build the firmware, you put it on a CH32V307, the result is USB comms with that microcontroller.

The CH32V307 is a STM32F3 peripherals compatible microcontroller using a RISC-V core.
